-   id: cspell
    name: cspell
    entry: cspell --no-must-find-files --no-progress
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["cspell@5.4.1"]
